### ISSUE TITLE
"Warning XSLT version ignored" output when using Jing with Saxon 11.4

### ISSUE THREAD

**Issue by rdeltour** [relaxng/jing-trang#277]
When using Jing with Saxon 11.4, the following warning is reported (when using Schematron)

```
Warning
  XSLT version ignored: only "3.0" is recognized
```

This is due to Jing's Saxon factory setting the `XSLT_VERSION` feature to "2.0" (in [NewSaxonSchemaReaderFactory](https://github.com/relaxng/jing-trang/blob/V20220510/mod/schematron/src/main/com/thaiopensource/validate/schematron/NewSaxonSchemaReaderFactory.java#L16)), which is reported by Saxon (in the [Configuration](https://saxonica.plan.io/projects/saxonmirrorhe/repository/he/revisions/he_mirror_saxon_11_4/entry/src/main/java/net/sf/saxon/Configuration.java#L4805) class).

I'm not quite sure since when Saxon reports that (probably since it implements XSLT 3.0).

The workaround I found in EPUBCheck (see https://github.com/w3c/epubcheck/pull/1448) is to provide a custom `SchematronSchemaReaderFactory` via SPI, which does not set that feature.

I don't know how to best silence this warning in Jing, or if Jing should try to to not set that feature when detecting Saxon's XSLT 3.0 support. Any advice @ndw?

**Comment by michaelhkay** [comment]
At one time (before 3.0 was finalised) Saxon had the option to operate as either a 2.0 or a 3.0 conformant processor. If you selected 2.0 (in the API), then we tried hard to suppress all 3.0 features such as new functions, xsl:iterate, etc. Simply setting version="2.0" in the stylesheet doesn't have this effect (3.0 features will still work, so you don't pass the conformance tests for 2.0). At some later date we decided we would no longer have a 2.0-conformant mode: if you request 2.0, we fall back to 3.0, so you get the 3.0 features whether you like it or not. We made this decision because the level of backwards compatibility between 2.0 and 3.0 is very high, so pretty well all non-error stylesheets will run unchanged. If you ask for 2.0 conformance, we can't meet your request, so we give a warning that we are falling back to 3.0. I think that's reasonable.

More recently we've been going through all the warning messages making sure they all have unique error codes so it's easier to suppress them in an ErrorReporter. It looks like I missed this one: I'll fix that.

**Comment by rdeltour** [comment]
Thanks for the explanation @michaelhkay!

> the level of backwards compatibility between 2.0 and 3.0 is very high, so pretty well all non-error stylesheets will run unchanged

so, can we safely assume that setting the "XSLT_VERSION" feature in Jing is effectively useless ? (or irrelevant even in Saxon versions which did have a 2.0-conformant mode?)

I'm trying to figure out if removing that configuration:

```
factory.setAttribute(FeatureKeys.XSLT_VERSION, "2.0");
```

would be a safe way to fix the issue on Jing's side, rather than asking users to suppress the warning in an ErrorReporter.

**Comment by rdeltour** [comment]
Ok, thanks for confirming, @michaelhkay!

**Comment by ndw** [comment]
What's especially problematic is that `SchematronSchemaReaderFactory` calls `this.newTransformerFactory()` without setting the error handler. So even if you have a custom error handler to filter out the spurious warning, it doesn't get used.
